### ISSUE TITLE
caddy-security v1.1.17 does not compile

### ISSUE THREAD

**Issue by assistcontrol** [greenpau/caddy-security#196]
```
# github.com/crewjam/saml
/root/go/pkg/mod/github.com/crewjam/saml@v0.4.10/schema.go:767:41: not enough arguments in call to etreeutils.TransformExcC14n
        have (*etree.Element, string)
        want (*etree.Element, string, bool)
```

I know that you've forked `crewjam/saml` into `origin_crewjam_saml`, but the schema fix is in a branch that isn't used by caddy-security. As a result, I believe that v1.1.17 can't build.

Given that the bug for the schema error has been sitting for months in @crewjam's repo and caddy-security's build is currently broken, what's your plan? Will caddy-security just not build temporarily until the upstream PR gets merged, or do you intend to merge your schema fix to your fork's main and use that?

**Comment by greenpau** [comment]
@assistcontrol , try doing `go mod tidy` followed by `go mod verify`.

**Comment by greenpau** [comment]
@assistcontrol , if you are building your own custom binary, add the following to `go.mod`:

https://github.com/greenpau/caddy-security/blob/4dd61acb5a23ebdf6334e3f36c34cf6e232e9233/go.mod#L154

**Comment by assistcontrol** [comment]
Agreed, that does let caddy-security build on its own. I should have been mentioned originally that I'm doing `xcaddy build --with github.com/greenpau/caddy-security`. FreeBSD does each build in a clean jail so there's nothing to tidy, and xcaddy doesn't make it easy to alter `go.mod` as an intermediate step.

**Comment by greenpau** [comment]
@assistcontrol , try passing the substitution/replace using xcaddy —with.

**Comment by assistcontrol** [comment]
Wow, I never realized xcaddy could do that. Thanks!

**Comment by greenpau** [comment]
@assistcontrol , please post your final build command 😃

**Comment by assistcontrol** [comment]
`xcaddy --with github.com/greenpau/caddy-security --with github.com/crewjam/saml@v0.4.10=github.com/greenpau/origin_crewjam_saml@v0.4.11-0.20221229165346-936eba92623a`

Works for me, and it's nicely future-proofed because the version is specified: if you update the dep in caddy-security, it won't drag old stuff in.

**Comment by greenpau** [comment]
working with @crewjam to address this here: https://github.com/crewjam/saml/pull/478

**Comment by crewjam** [comment]
Just highlighting that as it stands the fix causes a security related test to fail, which is why it has stalled. I haven't looked at the fork but I'd urge a little bit of caution here.

**Comment by mattjm** [comment]
@crewjam  Not having dug into the code too much and not being an expert on XML canonicalization, from what I can see passing "false" to the method means comments won't be considered for canonicalization.  At first I thought "how could that possibly be a problem?" But it looks like maybe it could be:

https://workos.com/blog/fun-with-saml-sso-vulnerabilities-and-footguns

Depending on the ordering of canonicalization vs signature verification steps.  I know SAML pretty well but not your library--if you want to discuss further let me know.

**Comment by crewjam** [comment]
Thanks @mattjm . I think @greenpau has it figured out.
